version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:4-standalone
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
volumes:
  postgres_data: